package co.novu.dto.response.subscribers

data class SubscriberNotificationResponse(
    var _id: String? = null,
    var _templateId: String? = null,
    var _environmentId: String? = null,
    var _messageTemplateId: String? = null,
    var _organizationId: String? = null,
    var _notificationId: String? = null,
    var _subscriberId: String? = null,
    var subscriber: Any? = null,
    var template: Any? = null,
    var templateIdentifier: String? = null,
    var createdAt: String? = null,
    var content: String? = null,
    var transactionId: String? = null,
    var channel: String? = null,
    var seen: Boolean? = null,
    var email: String? = null,
    var phone: String? = null,
    var directWebhookUrl: String? = null,
    var providerId: String? = null,
    var deviceTokens: List<String>? = null,
    var title: String? = null,
    var lastSeenDate: String? = null,
    var cta: Any? = null,
    var _feedId: String? = null,
    var status: String? = null,
    var errorId: String? = null,
    var errorText: String? = null,
    var payload: Any? = null,
    var overrides: Any? = null,
    var subject: Any? = null
)
