package co.novu.dto.response.subscribers

data class SubscriberNotificationResponse(
    var _id: String?,
    var _templateId: String?,
    var _environmentId: String?,
    var _messageTemplateId: String?,
    var _organizationId: String?,
    var _notificationId: String?,
    var _subscriberId: String?,
    var subscriber: Any?,
    var template: Any?,
    var templateIdentifier: String?,
    var createdAt: String?,
    var content: String?,
    var transactionId: String?,
    var channel: String?,
    var seen: Boolean?,
    var email: String?,
    var phone: String?,
    var directWebhookUrl: String?,
    var providerId: String?,
    var deviceTokens: List<String>?,
    var title: String?,
    var lastSeenDate: String?,
    var cta: Any,
    var _feedId: String?,
    var status: String?,
    var errorId: String?,
    var errorText: String?,
    var payload: Any?,
    var overrides: Any?,
    var subject: Any?,
)
